name: CI Checks

on:
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint # Runs ESLint to check for linting issues
      - name: Run Tests
        run: npm test # Runs tests (e.g., Jest, Vitest)
      - name: Build Project
        run: npm run build # Ensures the project builds without errors